apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.AppName }}
  namespace: {{ .Values.NameSpace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
    spec:
      containers:
      - name: {{ .Values.AppName }}
        image: {{ .Values.DockerImage }}
        ports:
        - containerPort: 8000
        env:
          - name: API_NAME
            value: {{ .Values.API_NAME }}
          - name: API_TAG_NAME
            value: {{ .Values.API_TAG_NAME }}
          - name: KEYCLOAK_HOST
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_HOST
          - name: KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_REALM
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_CLIENT_ID
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_CLIENT_SECRET
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: REDIS_PORT
          - name: REDIS_DB
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: REDIS_DB
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: REDIS_PASSWORD