apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.AppName }}-service
  namespace: {{ .Values.NameSpace }}
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: {{ .Values.AppName }}